services:
  - type: web
    name: auction-app
    env: node
    plan: free
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm run start
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      # Updated to match Auth.js v5 naming convention
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false

      # Add the missing NEXTAUTH_URL for production
      - key: NEXTAUTH_URL
        value: https://auction-app-u4q7.onrender.com

      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false

      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_KEY
        sync: false
      - key: PUSHER_SECRET
        sync: false
      - key: PUSHER_CLUSTER
        sync: false

      - key: NEXT_PUBLIC_PUSHER_KEY
        sync: false
      - key: NEXT_PUBLIC_PUSHER_CLUSTER
        sync: false

      - key: ADMIN_EMAILS
        sync: false
